# Generated by Django 4.0.6 on 2022-07-31 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
        ('cloudserviceproviderapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Plan_Request',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_purchased', models.CharField(help_text='userpurchased', max_length=50, null=True)),
                ('user_upload_times', models.CharField(default=0, max_length=50)),
                ('user_card_no', models.CharField(help_text='user_card_no', max_length=500, null=True)),
                ('purchased_price', models.CharField(help_text='purchased_price', max_length=500, null=True)),
                ('user_address', models.CharField(help_text='user_address', max_length=500, null=True)),
                ('storage_purchased_converted', models.CharField(help_text='storage_purchased_converted', max_length=500, null=True)),
                ('storage_purchased', models.CharField(help_text='storage_purchased', max_length=500, null=True)),
                ('debited_storage', models.CharField(default=0, help_text='debited_storage', max_length=500)),
                ('cloud_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cloudserviceproviderapp.provider_add_services')),
                ('user_plan_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.user_registration')),
            ],
            options={
                'db_table': 'user_request_plan_details',
            },
        ),
    ]
