# Generated by Django 4.0.6 on 2022-07-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_registration',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(help_text='user_name', max_length=50)),
                ('user_email', models.EmailField(help_text='email', max_length=50)),
                ('user_mobile', models.BigIntegerField(help_text='mobile_no')),
                ('user_date_of_birth', models.CharField(help_text='user_birth', max_length=50)),
                ('user_password', models.CharField(help_text='user_password', max_length=50)),
                ('user_status', models.CharField(default='Pending', max_length=50)),
                ('user_service_request_status', models.CharField(default='0', max_length=50)),
                ('user_profile_upload', models.FileField(help_text='user_profile', max_length=50, upload_to='userprofile')),
            ],
            options={
                'db_table': 'user_registraion_details',
            },
        ),
    ]
