# Generated by Django 4.0.6 on 2022-07-31 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudserviceproviderapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider_add_services',
            name='user_reviews',
            field=models.CharField(default='0', help_text='user_reviews', max_length=70),
        ),
    ]
