# Generated by Django 4.0.6 on 2022-07-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudserviceproviderapp', '0002_alter_provider_add_services_user_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reviews_feedbacks',
            name='user_review',
            field=models.CharField(default='0', help_text='user_reviews', max_length=70),
        ),
    ]
