# Generated by Django 4.0.6 on 2022-07-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudserviceproviderapp', '0003_alter_user_reviews_feedbacks_user_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useruploadfile',
            name='upload_file',
            field=models.FileField(help_text='user_upload_image ', max_length=5000, null=True, upload_to='user_files'),
        ),
    ]
