# Generated by Django 4.0.6 on 2022-07-31 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloudserviceproviderapp', '0004_alter_useruploadfile_upload_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useruploadfile',
            name='download_rank',
        ),
        migrations.RemoveField(
            model_name='useruploadfile',
            name='search_rank',
        ),
        migrations.RemoveField(
            model_name='useruploadfile',
            name='update_rank',
        ),
        migrations.RemoveField(
            model_name='useruploadfile',
            name='user_upload_id',
        ),
        migrations.RemoveField(
            model_name='useruploadfile',
            name='view_rank',
        ),
    ]
